version: "3"

services:
    zookeeper:
        image: zookeeper
        restart: always

    traefik:
        restart: always
        image: traefik:alpine
        depends_on: 
            - zookeeper
        links:
            - modoki # --traefikAddr of modoki
        ports: 
            - 80:80
            - 443:443
        volumes:
            - "./traefik:/usr/local/traefik"
        command:
            - --configfile=/usr/local/traefik/traefik.toml
            - --web
            - --zookeeper
            - --zookeeper.endpoint=zookeeper:2181
            - --zookeeper.prefix=traefik
            - --zookeeper.watch=true
            - --debug

    modoki:
        restart: always
        build: .
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./cred:/usr/local/modoki/cred
        depends_on:
            - mysql
            - zookeeper
        command:
            - --db=root:${DB_PASSWORD}@tcp(mysql:3306)/modoki?charset=utf8mb4&parseTime=True
            - --zookeeper=zookeeper:2181
            - --docker-api=v1.37
            - --traefikAddr=http://modoki
            - --jwtkey=/usr/local/modoki/cred/jwt.example.key
            - --jwtpub=/usr/local/modoki/cred/jwt.example.key.pub
            

    mysql:
        restart: always
        volumes:
            - mysql-volume:/var/lib/mysql
        image: mysql
        user: mysql
        command: 
            - mysqld
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        environment: 
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: modoki

volumes:
    mysql-volume:
        driver: local
