defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
acmeLogging = true
storage = "/traefik/acme/account"
entryPoint = "https"
[acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0